# These are supported funding model platforms

github: captainAbdisamad-orgnasation,077so
patreon: captainAbdisamad
open_collective: captainAbdisamad
ko_fi: captainAbdisamad
tidelift: # captainAbdisamad
community_bridge: captainAbdisamad
liberapay: captainAbdisamad
issuehunt: captainAbdisamad
otechie: captainAbdisamad
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
